# Vectors and Matrices in Numpy - Lab

## Introduction

This lab will ask you to perform some simple matrix creation and manipulation exercises based on what we have covered so far in this section. The key takeaway here for you is to be able to understand how to using indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays A (4x2) and B (2x3) 
```
A = 1402, 191 
    1371, 821 
    949, 1437
    147, 1448
    
B = 1, 2, 3
    4, 5, 6
    ```

In [1]:
import numpy as np

In [2]:
A= np.array([[1402, 191], [1371, 821], [949, 1437], [147, 1448]])
B= np.array([[1,2,3], [4,5,6]])

In [3]:
# Code Here
print(A)
print(B)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of A and B 

In [4]:
print(A.shape)
print(B.shape)

(4, 2)
(2, 3)


In [5]:
# Code Here

## 3. Print some of the elements from A at following locations
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [6]:
A[0,0] # element in the first row and first column

1402

In [7]:
A[0] # first_row

array([1402,  191])

In [8]:
A[0,1] # element for first row and 2nd column

191

In [9]:
A[2,1] # element for third row and 2nd column

1437

In [10]:
A[3,0] # element for fourth row and first column

147

## 4. Write a routine to populate matrix with random data
* Create an 3x3 numpy array with all zeros (use `np.zeros()`)
* Access each location i,j of this matrix and fill in random values between the range 1 and 10. 

In [54]:
# Code Here (due to random data , your output might be different)

before random data:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

after random data:
 [[2. 7. 5.]
 [7. 9. 3.]
 [6. 5. 9.]]


In [11]:
before = np.zeros([3,3])
after = before.copy()
for i in range(3):
    for j in range(3):
         after[i,j] += np.random.randint(1, 10)
        
print(before)
print(after)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[8. 9. 5.]
 [9. 7. 6.]
 [4. 1. 2.]]


## 5. Turn above routine into a function.
* Create two 4x4 zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [12]:
import itertools as it

In [21]:
x = np.zeros([3,4,3])
def array_ind(array):
    sh = array.shape
    length = len(array.shape)
    lst = list(range(max(sh)))
    ind_comb_1 = set(it.combinations_with_replacement(lst, length))
    ind_comb_2 = set(it.permutations(lst*2, length))
    indices = list(ind_comb_1|ind_comb_2)
    idx_final = indices.copy()
    for i in range(length):
        for perm in indices:
            if perm[i] >= sh[i]:
                if perm in idx_final:
                    idx_final.remove(perm)
            idx_final.sort()
    return idx_final    

y = array_ind(x)
print(y)

[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 2, 0), (0, 2, 1), (0, 2, 2), (0, 3, 0), (0, 3, 1), (0, 3, 2), (1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 2, 0), (1, 2, 1), (1, 2, 2), (1, 3, 0), (1, 3, 1), (1, 3, 2), (2, 0, 0), (2, 0, 1), (2, 0, 2), (2, 1, 0), (2, 1, 1), (2, 1, 2), (2, 2, 0), (2, 2, 1), (2, 2, 2), (2, 3, 0), (2, 3, 1), (2, 3, 2)]


In [28]:
x = np.zeros([3,4,3])
for ind in y:
    x[ind] = np.random.randint(1, 100)
print(x[2,3,1])

58.0


In [29]:
def create_random_matrix(zero_matrix, range_min, range_max):
    result = zero_matrix.copy()
    sh = result.shape
    for i in range(sh[0]):
        for j in range(sh[1]):
            result[i,j] += np.random.randint(range_min, range_max)
    return result

In [30]:
nza = np.zeros([4,4])
create_random_matrix(nza, 1, 20)

array([[19.,  9., 16.,  2.],
       [16., 12.,  1., 14.],
       [ 5.,  6., 19.,  4.],
       [14.,  1., 13., 14.]])

In [34]:
nza1 = np.zeros([4,5, 4])
create_random_tensor(nza1, 1, 100)

array([[[28., 72., 17., 62.],
        [53., 16.,  9., 67.],
        [26., 41., 45., 42.],
        [30., 95., 90., 18.],
        [49., 36., 50., 10.]],

       [[12., 78., 79., 94.],
        [35., 19., 17., 56.],
        [43., 34., 63., 64.],
        [76., 96., 43., 41.],
        [22., 66., 40., 16.]],

       [[99., 55., 80.,  8.],
        [29.,  5.,  1., 13.],
        [55., 96., 85., 44.],
        [76., 64., 28., 69.],
        [60., 72., 98., 68.]],

       [[ 5., 85., 95., 96.],
        [ 9., 94., 19., 78.],
        [63., 96., 22., 64.],
        [ 7., 19., 63., 47.],
        [76., 95., 50., 10.]]])

In [32]:
def create_random_tensor(tensor, range_min, range_max):
    result = tensor.copy()
    indices = array_ind(tensor)
    for ind in indices:
        result[ind] = np.random.randint(range_min, range_max)
    return result

In [55]:
# Code Here (due to random data , your output might be different)

Final output

 [[12.  4. 13.  8.]
 [13.  5.  9.  9.]
 [11. 11. 11. 17.]
 [16. 14.  8. 10.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 